INSERT INTO USER (ID, USERID, USERPASSWORD, USERNAME, USEREMAIL) VALUES (1, 'miroku', '1234', '미로쿠', 'miroku@miroku.com');
INSERT INTO USER (ID, USERID, USERPASSWORD, USERNAME, USEREMAIL) VALUES (2, 'gazio', '1234', '가지오', 'gazio@gazio.com');

INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (1, 1, '질문입니다', '테스트 질문입니다', CURRENT_TIMESTAMP());
INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE) VALUES (2, 2, '이렇게 하면되나요?', '이렇게 하면 되겠죠', CURRENT_TIMESTAMP());